### PR TITLE
Fix the link to the website in the readme

### PR DESCRIPTION
**Pull request by FSMaxB**

### CODE REVIEW

**Comment by macaullyjames** [comment]
Thanks for the PR, I've been meaning to fix that for a while now :)

**Comment by macaullyjames** [comment]
How did you find this anyway? 😊

**Comment by FSMaxB** [comment]
I was searching for implementations of correcthorsebattery style password generators on GitHub, because the first one I ever encountered was insecure, so I decided to take a look at what else I can find.

When I wanted to take a look at the website, I found out that the link is broken. The Website looks nice btw.

**Comment by macaullyjames** [comment]
Thanks! Yeah, there's an inherent problem of trust when letting a web service choose a password for you; unless you're checking the source after every browser refresh it's hard be sure that you're actually getting what was promised.

**Pull request merged**
